[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/2024.07.00/platform-espressif32.zip
; board = esp32dev
board = upesy_wroom
framework = arduino
monitor_speed = 115200

monitor_filters = esp32_exception_decoder
build_type = debug

lib_deps =
  santerilindfors/WiFiProvisioner@2.0.0

build_flags = 
    -D ARDUINO_LOOP_STACK_SIZE=16384

; build_flags =
;   -std=gnu++17
